<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test PHP</title>
</head>

<body>

    <h1> from HTML </h1>

    <?php
    echo '<h2> generated by PHP</h2>';
    ?>

    <?= '<h3>Shortcut echo</h3>' ?>
</body>

</html>